// generated by generateIconListing.ts - Tue Sep 22 2026 18:29:37 GMT-0400 (Eastern Daylight Time)

import Android from "./android.svelte";
import Bun from "./bun.svelte";
import Css from "./css.svelte";
import Docker from "./docker.svelte";
import Fastify from "./fastify.svelte";
import Figma from "./figma.svelte";
import Git from "./git.svelte";
import Github from "./github.svelte";
import Html5 from "./html5.svelte";
import Javascript from "./javascript.svelte";
import Kicad from "./kicad.svelte";
import Kotlin from "./kotlin.svelte";
import Lua from "./lua.svelte";
import Micropython from "./micropython.svelte";
import Nextjs from "./nextjs.svelte";
import Postgresql from "./postgresql.svelte";
import Prisma from "./prisma.svelte";
import Python from "./python.svelte";
import React from "./react.svelte";
import Sass from "./sass.svelte";
import Svelte from "./svelte.svelte";
import Tailwindcss from "./tailwindcss.svelte";
import Typescript from "./typescript.svelte";

const index = {
	android: Android,
	bun: Bun,
	css: Css,
	docker: Docker,
	fastify: Fastify,
	figma: Figma,
	git: Git,
	github: Github,
	html5: Html5,
	javascript: Javascript,
	kicad: Kicad,
	kotlin: Kotlin,
	lua: Lua,
	micropython: Micropython,
	nextjs: Nextjs,
	postgresql: Postgresql,
	prisma: Prisma,
	python: Python,
	react: React,
	sass: Sass,
	svelte: Svelte,
	tailwindcss: Tailwindcss,
	typescript: Typescript,
}

export default index;