// generated by generateIconListing.ts - Fri Sep 25 2026 01:48:01 GMT-0400 (Eastern Daylight Time)

import Android from "./android.svelte";
import Bun from "./bun.svelte";
import Css from "./css.svelte";
import Discord from "./discord.svelte";
import Docker from "./docker.svelte";
import Externallink from "./externallink.svelte";
import Fastify from "./fastify.svelte";
import Figma from "./figma.svelte";
import Git from "./git.svelte";
import Github from "./github.svelte";
import Gradle from "./gradle.svelte";
import Html5 from "./html5.svelte";
import Javascript from "./javascript.svelte";
import Kicad from "./kicad.svelte";
import Kotlin from "./kotlin.svelte";
import Lua from "./lua.svelte";
import Mail from "./mail.svelte";
import Micropython from "./micropython.svelte";
import Modrinth from "./modrinth.svelte";
import Nextjs from "./nextjs.svelte";
import Postgresql from "./postgresql.svelte";
import Prisma from "./prisma.svelte";
import Python from "./python.svelte";
import React from "./react.svelte";
import Sass from "./sass.svelte";
import Svelte from "./svelte.svelte";
import Tailwindcss from "./tailwindcss.svelte";
import Typescript from "./typescript.svelte";
import Vite from "./vite.svelte";

const index = {
	android: Android,
	bun: Bun,
	css: Css,
	discord: Discord,
	docker: Docker,
	externallink: Externallink,
	fastify: Fastify,
	figma: Figma,
	git: Git,
	github: Github,
	gradle: Gradle,
	html5: Html5,
	javascript: Javascript,
	kicad: Kicad,
	kotlin: Kotlin,
	lua: Lua,
	mail: Mail,
	micropython: Micropython,
	modrinth: Modrinth,
	nextjs: Nextjs,
	postgresql: Postgresql,
	prisma: Prisma,
	python: Python,
	react: React,
	sass: Sass,
	svelte: Svelte,
	tailwindcss: Tailwindcss,
	typescript: Typescript,
	vite: Vite,
}

export type Icons = keyof typeof index;
export default index;
