import Bun from 'bun';

const glob = new Bun.Glob('*.svelte');
const list: string[] = [];

for (const file of glob.scanSync('./src/lib/icons/')) {
	list.push(file);
}

let data = `// generated by generateIconListing.ts - ${new Date()}\n\n`;

list.forEach((item) => {
	const name = item.substring(0, item.length - 7);
	const uppercase = name.substring(0, 1).toUpperCase() + name.substring(1).toLowerCase();

	data += `import ${uppercase} from "./${item}";\n`;
});

data += '\n';
data += `const index = {\n`;

list.forEach((item) => {
	const name = item.substring(0, item.length - 7);
	const uppercase = name.substring(0, 1).toUpperCase() + name.substring(1).toLowerCase();

	data += `\t${name}: ${uppercase},\n`;
});

data += '}\n';
data += '\n';
data += 'export default index;';

console.log(data);
await Bun.write('./src/lib/icons/index.ts', data);
